// src/components/ProfessionalLinks.tsx
'use client'

import React from 'react'
import { motion } from 'framer-motion'
import { Briefcase, FileDown } from 'lucide-react'

// Ícone do LinkedIn em SVG (removido das versões recentes do Lucide)
const LinkedInIcon = ({ size = 16, className = "" }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
  >
    <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
    <rect width="4" height="12" x="2" y="9" />
    <circle cx="4" cy="4" r="2" />
  </svg>
)

export default function ProfessionalLinks({ id }: { id?: string }) {
  return (
    <section id={id} className="py-20 bg-primary relative transition-colors duration-300">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true, margin: '-50px' }}
          transition={{ duration: 0.5, ease: 'easeOut' }}
          className="max-w-3xl mx-auto p-12 bg-primary border border-border-custom rounded-2xl text-center"
        >
          <h2 className="text-3xl font-extrabold text-txt-primary mb-4 tracking-tight">
            Vamos nos <span className="opacity-40 font-normal">conectar?</span>
          </h2>
          <p className="text-txt-secondary text-base mb-8 max-w-lg mx-auto">
            Estou sempre aberto a novas oportunidades e conexões. Veja meu perfil completo e recomendações nestas plataformas.
          </p>

          <div className="flex flex-col sm:flex-row justify-center items-center gap-4">
            <motion.a
              whileHover={{ y: -2 }}
              whileTap={{ scale: 0.98 }}
              href="https://linkedin.com/in/seuusuario"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center gap-2 px-6 py-3 bg-[#0a66c2] text-white border border-[#0a66c2] rounded-lg font-semibold w-full sm:w-auto transition-opacity hover:opacity-90"
            >
              <LinkedInIcon size={18} />
              <span>LinkedIn</span>
            </motion.a>

            <motion.a
              whileHover={{ y: -2 }}
              whileTap={{ scale: 0.98 }}
              href="https://glassdoor.com"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center gap-2 px-6 py-3 bg-primary text-txt-primary border border-border-custom hover:border-txt-primary rounded-lg font-semibold w-full sm:w-auto transition-colors"
            >
              <Briefcase size={18} />
              <span>Glassdoor</span>
            </motion.a>

            <motion.a
              whileHover={{ y: -2 }}
              whileTap={{ scale: 0.98 }}
              href="/curriculo.pdf"
              download
              className="flex items-center justify-center gap-2 px-6 py-3 bg-txt-primary text-primary border border-txt-primary hover:bg-transparent hover:text-txt-primary rounded-lg font-semibold w-full sm:w-auto transition-colors"
            >
              <FileDown size={18} />
              <span>Baixar CV</span>
            </motion.a>
          </div>
        </motion.div>
      </div>
    </section>
  )
}

// old-vue-backup/src/components/ProfessionalLinks.vue
<template>
  <section id="contato-profissional" class="section professional-links">
    <div class="container">
      <div class="professional-card" data-aos="zoom-in">
        <h2 class="professional-title">Vamos nos <span class="muted">conectar?</span></h2>
        <p class="professional-description">
          Estou sempre aberto a novas oportunidades e conexões. Veja meu perfil completo e recomendações nestas plataformas.
        </p>
        <div class="links-grid">
          <a href="https://linkedin.com/in/seuusuario" target="_blank" class="link-item linkedin">
             <font-awesome-icon :icon="['fab', 'linkedin']" />
            <span>LinkedIn</span>
          </a>
          <a href="https://glassdoor.com" target="_blank" class="link-item glassdoor">
             <font-awesome-icon :icon="['fas', 'briefcase']" />
            <span>Glassdoor</span>
          </a>
          <a href="/curriculo.pdf" download class="link-item cv">
             <font-awesome-icon :icon="['fas', 'file-pdf']" />
            <span>Baixar CV</span>
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'ProfessionalLinks'
}
</script>

<style scoped>
.professional-card {
  background: var(--bg-primary);
  border: 1px solid var(--border);
  border-radius: 16px;
  padding: 48px;
  text-align: center;
  max-width: 800px;
  margin: 0 auto;
}

.professional-title {
  font-size: 2rem;
  font-weight: 800;
  margin-bottom: 16px;
  letter-spacing: -0.05em;
}

.professional-description {
  color: var(--text-secondary);
  font-size: 1.1rem;
  margin-bottom: 32px;
  line-height: 1.5;
}

.links-grid {
  display: flex;
  justify-content: center;
  gap: 16px;
  flex-wrap: wrap;
}

.link-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 24px;
  border-radius: 8px;
  font-weight: 600;
  text-decoration: none;
  transition: all 0.2s ease;
  font-size: 1rem;
  border: 1px solid var(--border);
}

.link-item.linkedin {
  background: #0a66c2;
  color: white;
  border-color: #0a66c2;
}

.link-item.glassdoor {
  background: var(--bg-primary);
  color: var(--text-primary);
}

.link-item.cv {
  background: var(--text-primary);
  color: var(--bg-primary);
}

.link-item:hover {
  transform: translateY(-2px);
  opacity: 0.9;
}

.muted {
  opacity: 0.4;
  font-weight: 400;
}

@media (max-width: 768px) {
  .professional-card {
    padding: 32px 20px;
  }
  
  .links-grid {
    flex-direction: column;
  }
  
  .link-item {
    justify-content: center;
  }
}
</style>
