// src/components/CustomCursor.vue
<template>
  <div class="cursor-container" v-if="!isMobile">
    <div 
      class="cursor-dot" 
      :style="{ left: cursorPos.x + 'px', top: cursorPos.y + 'px' }"
      :class="{ 'cursor-hover': isHovering }"
    ></div>
    <div 
      class="cursor-outline" 
      :style="{ left: cursorOutlinePos.x + 'px', top: cursorOutlinePos.y + 'px' }"
      :class="{ 'cursor-hover': isHovering }"
    ></div>
  </div>
</template>

<script>
import { ref, onMounted, onBeforeUnmount } from 'vue'

export default {
  name: 'CustomCursor',
  setup() {
    const cursorPos = ref({ x: 0, y: 0 })
    const cursorOutlinePos = ref({ x: 0, y: 0 })
    const isHovering = ref(false)
    const isMobile = ref(false)

    let animationId = null

    const updateCursor = (e) => {
      cursorPos.value = { x: e.clientX, y: e.clientY }
    }

    const animateOutline = () => {
      const dx = cursorPos.value.x - cursorOutlinePos.value.x
      const dy = cursorPos.value.y - cursorOutlinePos.value.y
      
      cursorOutlinePos.value.x += dx * 0.1
      cursorOutlinePos.value.y += dy * 0.1
      
      animationId = requestAnimationFrame(animateOutline)
    }

    const handleMouseEnter = () => {
      isHovering.value = true
    }

    const handleMouseLeave = () => {
      isHovering.value = false
    }

    const checkMobile = () => {
      isMobile.value = window.innerWidth <= 768 || 'ontouchstart' in window
    }

    onMounted(() => {
      checkMobile()
      
      if (!isMobile.value) {
        document.addEventListener('mousemove', updateCursor)
        animateOutline()

        // Add hover effects to interactive elements
        const interactiveElements = document.querySelectorAll('a, button, .project-card, .tech-card-carousel')
        interactiveElements.forEach(el => {
          el.addEventListener('mouseenter', handleMouseEnter)
          el.addEventListener('mouseleave', handleMouseLeave)
        })

        // Hide default cursor
        document.body.style.cursor = 'none'
      }

      window.addEventListener('resize', checkMobile)
    })

    onBeforeUnmount(() => {
      if (animationId) cancelAnimationFrame(animationId)
      document.removeEventListener('mousemove', updateCursor)
      document.body.style.cursor = 'auto'
      window.removeEventListener('resize', checkMobile)
    })

    return {
      cursorPos,
      cursorOutlinePos,
      isHovering,
      isMobile
    }
  }
}
</script>

<style scoped>
.cursor-container {
  position: fixed;
  top: 0;
  left: 0;
  pointer-events: none;
  z-index: 9999;
}

.cursor-dot {
  position: fixed;
  width: 6px;
  height: 6px;
  background: var(--text-primary);
  border-radius: 50%;
  transform: translate(-50%, -50%);
  transition: transform 0.2s ease;
  z-index: 10001;
}

.cursor-outline {
  position: fixed;
  width: 32px;
  height: 32px;
  border: 1px solid var(--text-primary);
  opacity: 0.3;
  border-radius: 50%;
  transform: translate(-50%, -50%);
  transition: transform 0.2s ease, opacity 0.2s ease;
  z-index: 10000;
}

.cursor-dot.cursor-hover {
  transform: translate(-50%, -50%) scale(0.5);
}

.cursor-outline.cursor-hover {
  transform: translate(-50%, -50%) scale(1.5);
  background: var(--text-primary);
  opacity: 0.15;
}
</style>

// src/components/CustomCursor.tsx
'use client'

import React, { useEffect, useState } from 'react'
import { motion, useMotionValue, useSpring } from 'framer-motion'

export default function CustomCursor() {
  const [isMobile, setIsMobile] = useState(true)
  const [isHovered, setIsHovered] = useState(false)

  // Motion values
  const mouseX = useMotionValue(-100)
  const mouseY = useMotionValue(-100)

  // Mola suave
  const springConfig = { damping: 30, stiffness: 300, mass: 0.6 }
  const cursorX = useSpring(mouseX, springConfig)
  const cursorY = useSpring(mouseY, springConfig)

  useEffect(() => {
    const checkMobile = () => {
      const isMobileDevice = 
        window.innerWidth <= 768 || 
        'ontouchstart' in window || 
        navigator.maxTouchPoints > 0
      setIsMobile(isMobileDevice)
    }

    checkMobile()
    window.addEventListener('resize', checkMobile)

    if (isMobile) return

    const handleMouseMove = (e: MouseEvent) => {
      mouseX.set(e.clientX)
      mouseY.set(e.clientY)
    }

    const handleMouseOver = (e: MouseEvent) => {
      const target = e.target as HTMLElement
      const isInteractive = 
        target.tagName === 'A' || 
        target.tagName === 'BUTTON' || 
        target.closest('a') || 
        target.closest('button') || 
        target.closest('.project-card') || 
        target.closest('.tech-card-carousel') ||
        target.classList.contains('cursor-pointer')

      setIsHovered(!!isInteractive)
    }

    document.body.style.cursor = 'none'

    window.addEventListener('mousemove', handleMouseMove)
    window.addEventListener('mouseover', handleMouseOver)

    return () => {
      window.removeEventListener('resize', checkMobile)
      window.removeEventListener('mousemove', handleMouseMove)
      window.removeEventListener('mouseover', handleMouseOver)
      document.body.style.cursor = 'auto'
    }
  }, [isMobile, mouseX, mouseY])

  if (isMobile) return null

  return (
    <div className="fixed top-0 left-0 pointer-events-none z-50">
      {/* Círculo externo Apple (cinza sutil com blur/mola) */}
      <motion.div
        style={{
          x: cursorX,
          y: cursorY,
          translateX: '-50%',
          translateY: '-50%',
        }}
        animate={{
          width: isHovered ? 40 : 22,
          height: isHovered ? 40 : 22,
          backgroundColor: isHovered ? 'rgba(0, 0, 0, 0.04)' : 'transparent',
          borderColor: isHovered ? 'rgba(29, 29, 31, 0.3)' : 'rgba(29, 29, 31, 0.15)',
        }}
        transition={{ type: 'tween', ease: 'easeOut', duration: 0.15 }}
        className="fixed rounded-full border border-txt-primary z-50 pointer-events-none"
      />

      {/* Ponto central discreto */}
      <motion.div
        style={{
          x: mouseX,
          y: mouseY,
          translateX: '-50%',
          translateY: '-50%',
        }}
        animate={{
          scale: isHovered ? 0.3 : 1,
          backgroundColor: isHovered ? 'rgba(29, 29, 31, 0.8)' : 'rgba(29, 29, 31, 0.6)',
        }}
        className="fixed w-1 h-1 rounded-full z-50 pointer-events-none"
      />
    </div>
  )
}
