// src/components/Footer.tsx
import React from 'react'
import Link from 'next/link'

export default function Footer() {
  const currentYear = new Date().getFullYear()

  return (
    <footer className="bg-secondary border-t border-border-custom/50 py-16 transition-colors duration-400">
      <div className="max-w-6xl mx-auto px-6">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-10 mb-12">
          {/* Logo e Descrição */}
          <div className="space-y-3">
            <h3 className="text-sm font-bold tracking-tight text-txt-primary">Bruno Bueno</h3>
            <p className="text-xs text-txt-secondary leading-relaxed">
              Desenvolvedor Full Stack de Software. Dedicado a construir experiências digitais limpas, fluidas e focadas no usuário.
            </p>
          </div>

          {/* Navegação */}
          <div className="space-y-4">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-txt-primary">Navegação</h4>
            <div className="flex flex-col space-y-2.5">
              <Link href="/" className="text-xs text-txt-secondary hover:text-txt-primary transition-colors w-fit">
                Início
              </Link>
              <Link href="/#projetos" className="text-xs text-txt-secondary hover:text-txt-primary transition-colors w-fit">
                Projetos
              </Link>
              <Link href="/#tecnologias" className="text-xs text-txt-secondary hover:text-txt-primary transition-colors w-fit">
                Tecnologias
              </Link>
              <Link href="/#sobre" className="text-xs text-txt-secondary hover:text-txt-primary transition-colors w-fit">
                Sobre
              </Link>
              <Link href="/#contato" className="text-xs text-txt-secondary hover:text-txt-primary transition-colors w-fit">
                Contato
              </Link>
            </div>
          </div>

          {/* Redes Sociais */}
          <div className="space-y-4">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-txt-primary">Social</h4>
            <div className="flex flex-col space-y-2.5">
              <a href="https://github.com" target="_blank" rel="noopener noreferrer" className="text-xs text-txt-secondary hover:text-txt-primary transition-colors w-fit">
                GitHub
              </a>
              <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="text-xs text-txt-secondary hover:text-txt-primary transition-colors w-fit">
                LinkedIn
              </a>
              <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" className="text-xs text-txt-secondary hover:text-txt-primary transition-colors w-fit">
                Instagram
              </a>
            </div>
          </div>
        </div>

        {/* Linha Final */}
        <div className="pt-8 border-t border-border-custom/50 flex flex-col sm:flex-row justify-between items-center gap-4">
          <p className="text-xs text-txt-muted">
            &copy; {currentYear} Bruno Bueno. Todos os direitos reservados.
          </p>
          <div className="flex space-x-6">
            <a href="#" className="text-xs text-txt-muted hover:text-txt-primary transition-colors">
              Privacidade
            </a>
            <a href="#" className="text-xs text-txt-muted hover:text-txt-primary transition-colors">
              Termos de Uso
            </a>
          </div>
        </div>
      </div>
    </footer>
  )
}

// src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="container">
      <div class="footer-content">
        <div class="footer-section">
          <h3>BB</h3>
          <p>Desenvolvedor Full Stack</p>
        </div>
        
        <div class="footer-section">
          <h4>Navegação</h4>
          <div class="footer-links">
            <router-link to="/">Início</router-link>
            <router-link to="/projetos">Projetos</router-link>
            <router-link to="/tecnologias">Tecnologias</router-link>
            <router-link to="/sobre">Sobre</router-link>
            <router-link to="/contato">Contato</router-link>
          </div>
        </div>
        
        <div class="footer-section">
          <h4>Social</h4>
          <div class="social-links">
            <a href="#" target="_blank">GitHub</a>
            <a href="#" target="_blank">Instagram</a>
            <a href="#" target="_blank">LinkedIn</a>
          </div>
        </div>
      </div>
      
      <div class="footer-bottom">
        <p>&copy; 2025 Bruno Bueno. Todos os direitos reservados.</p>
        <div class="footer-bottom-links">
          <a href="#">Política de Privacidade</a>
          <a href="#">Termos de Uso</a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer'
}
</script>

<style scoped>
.footer {
  background: var(--bg-secondary);
  border-top: 1px solid var(--border);
  padding: 60px 0 24px;
}

.footer-content {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 40px;
  margin-bottom: 40px;
}

.footer-section h3 {
  color: var(--accent);
  font-size: 1.5rem;
  margin-bottom: 16px;
}

.footer-section h4 {
  color: var(--text-primary);
  margin-bottom: 16px;
}

.footer-section p {
  color: var(--text-secondary);
}

.footer-links,
.social-links {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.footer-links a,
.social-links a {
  color: var(--text-secondary);
  text-decoration: none;
  transition: color 0.3s ease;
}

.footer-links a:hover,
.social-links a:hover {
  color: var(--accent);
}

.footer-bottom {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: 24px;
  border-top: 1px solid var(--border);
  flex-wrap: wrap;
  gap: 16px;
}

.footer-bottom p {
  color: var(--text-muted);
  font-size: 0.9rem;
}

.footer-bottom-links {
  display: flex;
  gap: 24px;
}

.footer-bottom-links a {
  color: var(--text-muted);
  text-decoration: none;
  font-size: 0.9rem;
  transition: color 0.3s ease;
}

.footer-bottom-links a:hover {
  color: var(--accent);
}

@media (max-width: 768px) {
  .footer-bottom {
    flex-direction: column;
    text-align: center;
  }
}
</style>
